name: build

on:
  push:

env:
  DRY_RUN: ${{ github.ref != 'refs/heads/master' }}


jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v2.3.4

      - name: prepare
        run: cinst ikvm --version 8.1.5717.20170308

      - name: build
        run: pwsh ./build.ps1

      - uses: actions/upload-artifact@v2
        with:
          name: packages
          path: bin/*.nupkg

      - name: deploy
        if: env.DRY_RUN != 'true'
        run: echo todo


